<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registro extends CI_Controller{
    var $session_data;
    function __construct()
    {
        parent::__construct();
        $this->load->model('Registro_model');
        $this->load->model('Producto_model');
       if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    
    /*
     * Listing of registro
     */
    function index()
    {
        $data['all_producto'] = $this->Producto_model->get_productos_activos();
        
        $data['_view'] = 'registro/index';
        $this->load->view('layouts/main',$data);
    }

    /*
    * registra la serie de un producto
    */
    function registrar_serie()
    {
        //if($this->acceso(104)) {
        $usuario_id = $this->session_data['usuario_id'];
        if ($this->input->is_ajax_request()) {
            $registro_fecha = date('Y-m-d');
            $registro_hora = date('H:i:s');
            $params = array(
                'producto_id' => $this->input->post('producto_id'),
                'usuario_id' => $usuario_id,
                'registro_serie' => $this->input->post('serie'),
                'registro_fecha' => $registro_fecha,
                'registro_hora' => $registro_hora,
                'registro_vigencia' => $this->input->post('registro_vigencia'),
            );
            $registro_id = $this->Registro_model->add_registro($params);
            
            echo json_encode("ok");
        }else{
            show_404();
        }
        //}
            
    }
    
    /*
    * mostras 
    */
    function buscar_registroproductos()
    {
        //if($this->acceso(104)) {
        if($this->input->is_ajax_request()){
            $producto_id = $this->input->post('producto_id');
            $datos = $this->Registro_model->get_registrosproducto($producto_id);
            echo json_encode($datos);
        }else{
            show_404();
        }
        //}
            
    }
    /*
     * Editing a registro
     */
    function edit($registro_id)
    {   
        // check if the registro exists before trying to edit it
        $data['registro'] = $this->Registro_model->get_registro($registro_id);
        if(isset($data['registro']['registro_id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
                    'producto_id' => $this->input->post('producto_id'),
                    'usuario_id' => $this->input->post('usuario_id'),
                    'registro_serie' => $this->input->post('registro_serie'),
                    'registro_fecha' => $this->input->post('registro_fecha'),
                    'registro_hora' => $this->input->post('registro_hora'),
                    'registro_vigencia' => $this->input->post('registro_vigencia'),
                );
                $this->Registro_model->update_registro($registro_id,$params);            
                redirect('registro/index');
            }
            else
            {
                $this->load->model('Producto_model');
                $data['all_producto'] = $this->Producto_model->get_productos_activos();
                
                $this->load->model('Usuario_model');
                $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();

                $data['_view'] = 'registro/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The registro you are trying to edit does not exist.');
    }
    
}
