<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get producto by producto_id
     */
    function get_producto($producto_id)
    {
        return $this->db->get_where('producto',array('producto_id'=>$producto_id))->row_array();
    }
        
    /*
     * Get all producto
     */
    function get_all_producto()
    {
        $this->db->order_by('producto_id', 'desc');
        return $this->db->get('producto')->result_array();
    }
        
    /*
     * function to add new producto
     */
    function add_producto($params)
    {
        $this->db->insert('producto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update producto
     */
    function update_producto($producto_id,$params)
    {
        $this->db->where('producto_id',$producto_id);
        return $this->db->update('producto',$params);
    }
    
    /*
     * function to delete producto
     */
    function delete_producto($producto_id)
    {
        return $this->db->delete('producto',array('producto_id'=>$producto_id));
    }
}
